'use client';
import { useState, type FormEvent } from 'react';
import { createBrowserClient } from '@supabase/ssr';

export function PurchaseCreateForm({ companyId, suppliers, items, projects }: { companyId: string; suppliers: any[]; items: any[]; projects: any[] }) {
 const [supplierId,setSupplierId]=useState(''); const [projectId,setProjectId]=useState(''); const [itemId,setItemId]=useState(items[0]?.id||''); const [qty,setQty]=useState('1'); const [price,setPrice]=useState(String(items[0]?.purchase_price||0)); const [description,setDescription]=useState(items[0]?.name||''); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const onItem=(id:string)=>{const i=items.find(x=>x.id===id);setItemId(id);setDescription(i?.name||'');setPrice(String(i?.purchase_price||0));};
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const s=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);const {error}=await s.rpc('create_purchase_document',{p_company_id:companyId,p_supplier_id:supplierId||null,p_project_id:projectId||null,p_issue_date:new Date().toISOString().slice(0,10),p_due_date:null,p_discount:0,p_notes:null,p_lines:[{item_id:itemId,description,quantity:Number(qty),unit_price:Number(price),discount:0,vat_rate:18}]});setMsg(error?error.message:'Achat créé.');setBusy(false);if(!error)window.location.reload();}
 return <form onSubmit={submit} className="card form-grid"><div><label className="label">Fournisseur</label><select className="input" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Sélectionner</option>{suppliers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><label className="label">Chantier</label><select className="input" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Aucun</option>{projects.map(p=><option key={p.id} value={p.id}>{p.reference} — {p.name}</option>)}</select></div><div><label className="label">Article</label><select className="input" value={itemId} onChange={e=>onItem(e.target.value)}>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div><label className="label">Quantité</label><input className="input" type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(e.target.value)}/></div><div><label className="label">Prix d'achat unitaire HT</label><input className="input" type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></div><div style={{gridColumn:'1/-1'}}><label className="label">Description</label><input className="input" value={description} onChange={e=>setDescription(e.target.value)}/></div><div><button className="btn btn-primary" disabled={busy}>{busy?'Création…':'Créer l’achat'}</button></div>{msg&&<div className="notice">{msg}</div>}</form>;
}
