'use client';
import { useState, type FormEvent } from 'react';

const types = [['client','Client'],['prospect','Prospect'],['supplier','Fournisseur'],['provider','Prestataire'],['subcontractor','Sous-traitant'],['other','Autre']];
export function ContactManager(){
 const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());const r=await fetch('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||'Erreur');setLoading(false);return;}window.location.reload();}
 if(!open)return <button className="btn btn-primary" onClick={()=>setOpen(true)}>+ Nouveau contact</button>;
 return <div className="modal-backdrop"><div className="modal card"><div className="page-head"><div><h2>Nouveau contact</h2><div className="muted">Créez une fiche réutilisable dans les ventes, achats et chantiers.</div></div><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Fermer</button></div><form onSubmit={submit}><div className="form-grid"><div><label className="label">Nom / raison sociale *</label><input className="input" name="name" required /></div><div><label className="label">Type *</label><select className="input" name="type" defaultValue="client">{types.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div><label className="label">Téléphone</label><input className="input" name="phone" /></div><div><label className="label">Email</label><input className="input" name="email" type="email" /></div><div><label className="label">Ville</label><input className="input" name="city" defaultValue="Abidjan" /></div><div><label className="label">Identifiant fiscal</label><input className="input" name="tax_id" /></div><div><label className="label">Limite de crédit</label><input className="input" name="credit_limit" type="number" min="0" defaultValue="0" /></div><div><label className="label">Adresse</label><input className="input" name="address" /></div></div><div style={{marginTop:14}}><label className="label">Notes</label><textarea className="input" name="notes" rows={3}/></div>{error&&<div className="error" style={{marginTop:14}}>{error}</div>}<button className="btn btn-primary" disabled={loading} style={{marginTop:16}}>{loading?'Enregistrement…':'Enregistrer le contact'}</button></form></div></div>
}
